version: '3.9'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}:${BUILD_LABEL}
    container_name: ${CONTAINER_NAME_PREFIX}
    hostname: ${CONTAINER_HOST_PREFIX}
    volumes:
      - ${HOST_PROJECT_DIRECTORY}:/var/www/html/application:rw
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./docker/php.ini:/etc/php/8.2/cli/conf.d/99-my.ini:ro
      - ./docker/root.zsh_history:/root/.zsh_history:rw
      - ./docker/user.zsh_history:/home/user/.zsh_history:rw
    networks:
      - docker_net
    ports:
      - ${CONTAINER_PORT_APP:-8787}:8787
      - ${CONTAINER_PORT_APP_VITE:-5173}:${CONTAINER_PORT_APP_VITE}
    working_dir: /var/www/html/application
    command: >
      bash -c "cron start;
      supervisord -c /etc/supervisor/conf.d/supervisord.conf;
      php /var/www/html/application/start.php start"
    restart: unless-stopped

networks:
  docker_net:
    driver: bridge
    name: ${CONTAINER_SHARING_NETWORK_NAME}
